name: Build list
on:
  push:
    branches: [ "*" ]
jobs:
  build-list:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Validate
      shell: bash
      run: ./build/validate.sh

