name: Build list
on:
  push:
    branches: [ "*" ]
jobs:
  build-list:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Validate
      shell: bash
      run: ./build/validate.sh
    - name: Build
      shell: bash
      run: ./build/build.sh
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: GitHub Commit & Push
      uses: actions-js/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
